import type { Subject } from './types';

export const examplePlan: { name: string; subjects: Subject[] } = {
  name: 'Computer Science (Example)',
  subjects: [
    {
      id: 'cs101',
      code: 'CS101',
      name: 'Introduction to Programming',
      hours: 6,
      prerequisites: [],
      category: 'Required',
      semester: 1,
    },
    {
      id: 'math101',
      code: 'MATH101',
      name: 'Calculus I',
      hours: 6,
      prerequisites: [],
      category: 'Required',
      semester: 1,
    },
    {
      id: 'cs102',
      code: 'CS102',
      name: 'Data Structures',
      hours: 6,
      prerequisites: ['cs101'],
      category: 'Required',
      semester: 2,
    },
    {
      id: 'math201',
      code: 'MATH201',
      name: 'Linear Algebra',
      hours: 5,
      prerequisites: ['math101'],
      category: 'Required',
      semester: 2,
    },
    {
      id: 'cs201',
      code: 'CS201',
      name: 'Algorithms',
      hours: 6,
      prerequisites: ['cs102', 'math101'],
      category: 'Required',
      semester: 3,
    },
    {
      id: 'cs210',
      code: 'CS210',
      name: 'Computer Architecture',
      hours: 5,
      prerequisites: ['cs101'],
      category: 'Required',
      semester: 3,
    },
    {
      id: 'cs301',
      code: 'CS301',
      name: 'Operating Systems',
      hours: 6,
      prerequisites: ['cs201', 'cs210'],
      category: 'Required',
      semester: 4,
    },
    {
      id: 'cs310',
      code: 'CS310',
      name: 'Databases',
      hours: 5,
      prerequisites: ['cs102'],
      category: 'Required',
      semester: 4,
    },
    {
      id: 'cs401',
      code: 'CS401',
      name: 'Software Engineering',
      hours: 6,
      prerequisites: ['cs301', 'cs310'],
      category: 'Required',
      semester: 5,
    },
    {
      id: 'cs420',
      code: 'CS420',
      name: 'Machine Learning',
      hours: 5,
      prerequisites: ['cs201', 'math201'],
      category: 'Elective',
      semester: 5,
    },
    {
      id: 'cs430',
      code: 'CS430',
      name: 'Computer Networks',
      hours: 5,
      prerequisites: ['cs301'],
      category: 'Elective',
      semester: 6,
    },
    {
      id: 'cs440',
      code: 'CS440',
      name: 'Capstone Project',
      hours: 8,
      prerequisites: ['cs401'],
      category: 'Required',
      semester: 6,
    },
  ],
};
